variable "region" {}
variable "B_vpc_cidr" {}
variable "A_vpc_cidr" {}
variable "subnet_B2_IP" {}
variable "subnet_B1_IP" {}
variable "subnet_B3_IP" {}
variable "subnet_B4_IP" {}
variable "subnet_B5_IP" {}
variable "subnet_B6_IP" {}
variable "subnet_B7_IP" {}
variable "subnet_B8_IP" {}
variable "subnet_A2_IP" {}
variable "subnet_A1_IP" {}
variable "subnet_A3_IP" {}
variable "subnet_A4_IP" {}
variable "subnet_A5_IP" {}
variable "subnet_A6_IP" {}
variable "subnet_A7_IP" {}
variable "subnet_A8_IP" {}